 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/github_repository_monitoring_configurations", type: :request do
  # GithubRepositoryMonitoringConfiguration. As you add validations to GithubRepositoryMonitoringConfiguration, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      GithubRepositoryMonitoringConfiguration.create! valid_attributes
      get github_repository_monitoring_configurations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      github_repository_monitoring_configuration = GithubRepositoryMonitoringConfiguration.create! valid_attributes
      get github_repository_monitoring_configuration_url(github_repository_monitoring_configuration)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_github_repository_monitoring_configuration_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      github_repository_monitoring_configuration = GithubRepositoryMonitoringConfiguration.create! valid_attributes
      get edit_github_repository_monitoring_configuration_url(github_repository_monitoring_configuration)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new GithubRepositoryMonitoringConfiguration" do
        expect {
          post github_repository_monitoring_configurations_url, params: { github_repository_monitoring_configuration: valid_attributes }
        }.to change(GithubRepositoryMonitoringConfiguration, :count).by(1)
      end

      it "redirects to the created github_repository_monitoring_configuration" do
        post github_repository_monitoring_configurations_url, params: { github_repository_monitoring_configuration: valid_attributes }
        expect(response).to redirect_to(github_repository_monitoring_configuration_url(GithubRepositoryMonitoringConfiguration.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new GithubRepositoryMonitoringConfiguration" do
        expect {
          post github_repository_monitoring_configurations_url, params: { github_repository_monitoring_configuration: invalid_attributes }
        }.to change(GithubRepositoryMonitoringConfiguration, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post github_repository_monitoring_configurations_url, params: { github_repository_monitoring_configuration: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested github_repository_monitoring_configuration" do
        github_repository_monitoring_configuration = GithubRepositoryMonitoringConfiguration.create! valid_attributes
        patch github_repository_monitoring_configuration_url(github_repository_monitoring_configuration), params: { github_repository_monitoring_configuration: new_attributes }
        github_repository_monitoring_configuration.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the github_repository_monitoring_configuration" do
        github_repository_monitoring_configuration = GithubRepositoryMonitoringConfiguration.create! valid_attributes
        patch github_repository_monitoring_configuration_url(github_repository_monitoring_configuration), params: { github_repository_monitoring_configuration: new_attributes }
        github_repository_monitoring_configuration.reload
        expect(response).to redirect_to(github_repository_monitoring_configuration_url(github_repository_monitoring_configuration))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        github_repository_monitoring_configuration = GithubRepositoryMonitoringConfiguration.create! valid_attributes
        patch github_repository_monitoring_configuration_url(github_repository_monitoring_configuration), params: { github_repository_monitoring_configuration: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested github_repository_monitoring_configuration" do
      github_repository_monitoring_configuration = GithubRepositoryMonitoringConfiguration.create! valid_attributes
      expect {
        delete github_repository_monitoring_configuration_url(github_repository_monitoring_configuration)
      }.to change(GithubRepositoryMonitoringConfiguration, :count).by(-1)
    end

    it "redirects to the github_repository_monitoring_configurations list" do
      github_repository_monitoring_configuration = GithubRepositoryMonitoringConfiguration.create! valid_attributes
      delete github_repository_monitoring_configuration_url(github_repository_monitoring_configuration)
      expect(response).to redirect_to(github_repository_monitoring_configurations_url)
    end
  end
end
