 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/github_repositories", type: :request do
  # GithubRepository. As you add validations to GithubRepository, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      GithubRepository.create! valid_attributes
      get github_repositories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      github_repository = GithubRepository.create! valid_attributes
      get github_repository_url(github_repository)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_github_repository_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      github_repository = GithubRepository.create! valid_attributes
      get edit_github_repository_url(github_repository)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new GithubRepository" do
        expect {
          post github_repositories_url, params: { github_repository: valid_attributes }
        }.to change(GithubRepository, :count).by(1)
      end

      it "redirects to the created github_repository" do
        post github_repositories_url, params: { github_repository: valid_attributes }
        expect(response).to redirect_to(github_repository_url(GithubRepository.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new GithubRepository" do
        expect {
          post github_repositories_url, params: { github_repository: invalid_attributes }
        }.to change(GithubRepository, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post github_repositories_url, params: { github_repository: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested github_repository" do
        github_repository = GithubRepository.create! valid_attributes
        patch github_repository_url(github_repository), params: { github_repository: new_attributes }
        github_repository.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the github_repository" do
        github_repository = GithubRepository.create! valid_attributes
        patch github_repository_url(github_repository), params: { github_repository: new_attributes }
        github_repository.reload
        expect(response).to redirect_to(github_repository_url(github_repository))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        github_repository = GithubRepository.create! valid_attributes
        patch github_repository_url(github_repository), params: { github_repository: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested github_repository" do
      github_repository = GithubRepository.create! valid_attributes
      expect {
        delete github_repository_url(github_repository)
      }.to change(GithubRepository, :count).by(-1)
    end

    it "redirects to the github_repositories list" do
      github_repository = GithubRepository.create! valid_attributes
      delete github_repository_url(github_repository)
      expect(response).to redirect_to(github_repositories_url)
    end
  end
end
